name: CDN Deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nebula-dev/spaces-sync-action@master
        env:
          SOURCE_DIR: "./scenes/"
          SPACE_REGION: "sfo3"
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
          SPACE_ACCESS_KEY: ${{ secrets.SPACE_ACCESS_KEY }}
          SPACE_SECRET_KEY: ${{ secrets.SPACE_SECRET_KEY }}
